-- public.vrm_skeleton_2022_03_28 definition

-- Drop table

-- DROP TABLE public.vrm_skeleton_2022_03_28;

CREATE TABLE public.vrm_skeleton_2022_03_28 (
	label STRING NOT NULL DEFAULT 'VRM_BONE_NONE':::STRING,
	bone STRING NOT NULL DEFAULT 'BONE_NONE':::STRING,
	bone_rest_x_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_y_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_z_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_x_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_x_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_x_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_y_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_y_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_truncated_normalized_basis_axis_y_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_x_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_y_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_rest_z_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_x_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_y_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_z_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_x_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_x_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_x_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_y_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_y_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_truncated_normalized_basis_axis_y_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_x_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_y_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_z_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_y_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_z_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_x_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_x_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_x_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_y_0 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_y_1 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_truncated_normalized_basis_axis_y_2 FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_x_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_y_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_parent_z_global_scale_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	bone_hierarchy STRING NOT NULL DEFAULT '':::STRING,
	specification_version STRING NOT NULL DEFAULT 'VRM_UNVERSIONED':::STRING,
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	bone_parent_x_global_origin_in_meters FLOAT4 NOT NULL DEFAULT 0.0:::FLOAT8,
	CONSTRAINT vrm_skeleton_2022_03_27_pk_1 PRIMARY KEY (id ASC),
	FAMILY "primary" (label, bone, bone_rest_x_global_origin_in_meters, bone_rest_y_global_origin_in_meters, bone_rest_z_global_origin_in_meters, bone_rest_truncated_normalized_basis_axis_x_0, bone_rest_truncated_normalized_basis_axis_x_1, bone_rest_truncated_normalized_basis_axis_x_2, bone_rest_truncated_normalized_basis_axis_y_0, bone_rest_truncated_normalized_basis_axis_y_1, bone_rest_truncated_normalized_basis_axis_y_2, bone_rest_x_global_scale_in_meters, bone_rest_y_global_scale_in_meters, bone_rest_z_global_scale_in_meters, bone_x_global_origin_in_meters, bone_y_global_origin_in_meters, bone_z_global_origin_in_meters, bone_truncated_normalized_basis_axis_x_0, bone_truncated_normalized_basis_axis_x_1, bone_truncated_normalized_basis_axis_x_2, bone_truncated_normalized_basis_axis_y_0, bone_truncated_normalized_basis_axis_y_1, bone_truncated_normalized_basis_axis_y_2, bone_x_global_scale_in_meters, bone_y_global_scale_in_meters, bone_z_global_scale_in_meters, bone_parent_y_global_origin_in_meters, bone_parent_z_global_origin_in_meters, bone_parent_truncated_normalized_basis_axis_x_0, bone_parent_truncated_normalized_basis_axis_x_1, bone_parent_truncated_normalized_basis_axis_x_2, bone_parent_truncated_normalized_basis_axis_y_0, bone_parent_truncated_normalized_basis_axis_y_1, bone_parent_truncated_normalized_basis_axis_y_2, bone_parent_x_global_scale_in_meters, bone_parent_y_global_scale_in_meters, bone_parent_z_global_scale_in_meters, bone_hierarchy, specification_version, id, bone_parent_x_global_origin_in_meters)
);