input_features:
  - name: vector
    type: vector
  - name: sink_bone_hierarchy
    type: sequence
  - name: source_bone_hierarchy
    type: sequence
output_features:
  - name: label
    type: binary
preprocessing:
  stratify: label
training:
  batch_size: 256
  threshold: 0.01
